two_letter_codes_set = {'kk', 'ug', 'la', 'ng', 'om', 'st', 'ga', 'nn', 'pa', 'br', 'ak', 'ia', 'te', 'no', 'fo', 'sm', 'sa', 'hi', 'pl', 'lb', 'el', 'li', 'cu', 'rw', 'bn', 'ht', 'sd', 'ff', 'ba', 'ie', 'jv', 'ne', 'tn', 'ky', 'ee', 'rm', 'zh', 'cv', 'io', 'na', 'az', 'wa', 'av', 'dv', 'id', 'th', 'ku', 'zu', 'tg', 'ta', 'ii', 'co', 'gn', 'yi', 'mh', 'cr', 'sc', 'ik', 'ab', 'ce', 'to', 'mr', 'ko', 'fj', 'nd', 'tl', 'tt', 'oj', 'bo', 'ar', 'kw', 'pt', 'ty', 'sv', 'tr', 'si', 'gd', 'ro', 'xh', 'se', 'gu', 'lv', 'ss', 'hz', 'uz', 've', 'ca', 'mk', 'hr', 'ha', 'iu', 'ts', 'nl', 'tw', 'vi', 'za', 'oc', 'ti', 'ay', 'it', 'lu', 'be', 'lt', 'nr', 'rn', 'pi', 'fa', 'su', 'fr', 'bg', 'tk', 'ki', 'aa', 'is', 'so', 'he', 'bm', 'ml', 'gl', 'qu', 'da', 'os', 'kl', 'vo', 'ig', 'ae', 'kr', 'es', 'sw', 'yo', 'ny', 'de', 'lg', 'ch', 'ho', 'ur', 'my', 'kj', 'hy', 'kv', 'ln', 'sk', 'mn', 'sl', 'ka', 'hu', 'wo', 'et', 'nv', 'kg', 'lo', 'cy', 'cs', 'fy', 'eu', 'kn', 'ks', 'gv', 'as', 'dz', 'sg', 'mg', 'nb', 'bs', 'km', 'or', 'fi', 'am', 'ja', 'mt', 'bi', 'ps', 'ru', 'mi', 'sr', 'sn', 'en', 'af', 'ms', 'uk', 'an', 'eo', 'sq'}

three_letter_codes_set = {'bur', 'tgk', 'lao', 'kik', 'pan', 'tir', 'hat', 'uig', 'mah', 'rum', 'ces', 'uzb', 'ton', 'iii', 'fao', 'kir', 'alb', 'tha', 'ina', 'glv', 'nya', 'wln', 'iku', 'eus', 'asm', 'gle', 'ewe', 'mya', 'kal', 'epo', 'kur', 'aka', 'orm', 'run', 'khm', 'msa', 'nbl', 'amh', 'san', 'mal', 'kat', 'ita', 'spa', 'tur', 'fry', 'srd', 'smo', 'ava', 'wol', 'pol', 'ven', 'nld', 'her', 'nau', 'sot', 'nor', 'vol', 'bak', 'kin', 'ger', 'nde', 'tat', 'pus', 'wel', 'kor', 'hye', 'arg', 'snd', 'tgl', 'swa', 'dzo', 'kas', 'vie', 'sqi', 'baq', 'bre', 'yid', 'aym', 'kau', 'chi', 'mkd', 'afr', 'lav', 'lit', 'ori', 'sun', 'cre', 'nob', 'lim', 'glg', 'mri', 'slk', 'ndo', 'hun', 'ara', 'mlg', 'roh', 'mlt', 'ben', 'sag', 'dut', 'hau', 'aze', 'tsn', 'kan', 'aar', 'geo', 'cze', 'mao', 'lug', 'lin', 'nep', 'swe', 'tib', 'isl', 'fas', 'kom', 'jav', 'bis', 'ssw', 'ibo', 'sna', 'fij', 'bos', 'chv', 'rus', 'ipk', 'que', 'hrv', 'kon', 'lat', 'tuk', 'abk', 'slo', 'lub', 'zho', 'hmo', 'div', 'oci', 'kaz', 'bul', 'xho', 'dan', 'ltz', 'slv', 'bod', 'ukr', 'yor', 'oss', 'ave', 'mon', 'est', 'jpn', 'ile', 'twi', 'sin', 'srp', 'ful', 'ido', 'ind', 'pli', 'tso', 'che', 'cos', 'som', 'cor', 'guj', 'oji', 'sme', 'urd', 'zul', 'tah', 'fin', 'gla', 'ell', 'arm', 'kua', 'mar', 'per', 'ice', 'fra', 'deu', 'cha', 'tam', 'tel', 'chu', 'cat', 'eng', 'hin', 'mac', 'fre', 'bam', 'heb', 'gre', 'grn', 'may', 'por', 'ron', 'nav', 'zha', 'cym', 'nno', 'bel'}

language_codes = two_letter_codes_set | three_letter_codes_set

libraries = {
    "PyTorch", "TensorFlow", "JAX", "Safetensors", "Transformers", "PEFT", "TensorBoard", "GGUF", "Diffusers", "ONNX", "stable-baselines3", "sentence-transformers", "ml-agents", "MLX", "TF-Keras", "Keras", "Adapters", "setfit", "timm", "Transformers.js", "sample-factory", "Joblib", "OpenVINO", "Flair", "fastai", "ESPnet", "BERTopic", "spaCy", "NeMo", "LiteRT", "Core ML", "OpenCLIP", "Rust", "Scikit-learn", "fastText", "KerasHub", "Asteroid", "speechbrain", "AllenNLP", "llamafile", "Fairseq", "PaddlePaddle", "Stanza", "Habana", "PaddleOCR", "Graphcore", "pyannote.audio", "SpanMarker", "paddlenlp", "unity-sentis", "DDUF", "univa"
}

multimodal_tasks = {
    "Audio-Text-to-Text",
    "Image-Text-to-Text",
    "Visual Question Answering",
    "Document Question Answering",
    "Video-Text-to-Text",
    "Visual Document Retrieval",
    "Any-to-Any",
}

computer_vision_tasks = {
    "Depth Estimation",
    "Image Classification",
    "Object Detection",
    "Image Segmentation",
    "Text-to-Image",
    "Image-to-Text",
    "Image-to-Image",
    "Image-to-Video",
    "Unconditional Image Generation",
    "Video Classification",
    "Text-to-Video",
    "Zero-Shot Image Classification",
    "Mask Generation",
    "Zero-Shot Object Detection",
    "Text-to-3D",
    "Image-to-3D",
    "Image Feature Extraction",
    "Keypoint Detection",
    "Video-to-Video",
}

nlp_tasks = {
    "Text Classification",
    "Token Classification",
    "Table Question Answering",
    "Question Answering",
    "Zero-Shot Classification",
    "Translation",
    "Summarization",
    "Feature Extraction",
    "Text Generation",
    "Fill-Mask",
    "Sentence Similarity",
    "Text Ranking",
}

audio_tasks = {
    "Text-to-Speech",
    "Text-to-Audio",
    "Automatic Speech Recognition",
    "Audio-to-Audio",
    "Audio Classification",
    "Voice Activity Detection",
}

tabular_tasks = {
    "Tabular Classification",
    "Tabular Regression",
    "Time Series Forecasting",
}

rl_tasks = {
    "Reinforcement Learning",
    "Robotics",
}

tasks = multimodal_tasks | computer_vision_tasks | nlp_tasks | audio_tasks | tabular_tasks | rl_tasks

reactoins = {'🚀', '🤗', '👀', '➕', '🤝', '❤️', '😎', '🔥', '😔', '👍', '🧠', '🤯'}

languages_3d = [
    ('Abkhazian', 'abk'),
    ('Afar', 'aar'),
    ('Afrikaans', 'afr'),
    ('Akan', 'aka'),
    ('Albanian', 'sqi'),
    ('Albanian', 'alb'),
    ('Amharic', 'amh'),
    ('Arabic', 'ara'),
    ('Aragonese', 'arg'),
    ('Armenian', 'hye'),
    ('Armenian', 'arm'),
    ('Assamese', 'asm'),
    ('Avaric', 'ava'),
    ('Avestan', 'ave'),
    ('Aymara', 'aym'),
    ('Azerbaijani', 'aze'),
    ('Bambara', 'bam'),
    ('Bashkir', 'bak'),
    ('Basque', 'eus'),
    ('Basque', 'baq'),
    ('Belarusian', 'bel'),
    ('Bengali', 'ben'),
    ('Bislama', 'bis'),
    ('Bosnian', 'bos'),
    ('Breton', 'bre'),
    ('Bulgarian', 'bul'),
    ('Burmese', 'mya'),
    ('Burmese', 'bur'),
    ('Catalan', 'cat'),
    ('Chamorro', 'cha'),
    ('Chechen', 'che'),
    ('Chichewa', 'nya'),
    ('Chinese', 'zho'),
    ('Chinese', 'chi'),
    ('Church Slavonic', 'chu'),
    ('Chuvash', 'chv'),
    ('Cornish', 'cor'),
    ('Corsican', 'cos'),
    ('Cree', 'cre'),
    ('Croatian', 'hrv'),
    ('Czech', 'ces'),
    ('Czech', 'cze'),
    ('Danish', 'dan'),
    ('Divehi', 'div'),
    ('Dutch', 'nld'),
    ('Dutch', 'dut'),
    ('Dzongkha', 'dzo'),
    ('English', 'eng'),
    ('Esperanto', 'epo'),
    ('Estonian', 'est'),
    ('Ewe', 'ewe'),
    ('Faroese', 'fao'),
    ('Fijian', 'fij'),
    ('Finnish', 'fin'),
    ('French', 'fra'),
    ('French', 'fre'),
    ('Western Frisian', 'fry'),
    ('Fulah', 'ful'),
    ('Gaelic', 'gla'),
    ('Galician', 'glg'),
    ('Ganda', 'lug'),
    ('Georgian', 'kat'),
    ('Georgian', 'geo'),
    ('German', 'deu'),
    ('German', 'ger'),
    ('Greek', 'ell'),
    ('Greek', 'gre'),
    ('Kalaallisut', 'kal'),
    ('Guarani', 'grn'),
    ('Gujarati', 'guj'),
    ('Haitian', 'hat'),
    ('Hausa', 'hau'),
    ('Hebrew', 'heb'),
    ('Herero', 'her'),
    ('Hindi', 'hin'),
    ('Hiri Motu', 'hmo'),
    ('Hungarian', 'hun'),
    ('Icelandic', 'isl'),
    ('Icelandic', 'ice'),
    ('Ido', 'ido'),
    ('Igbo', 'ibo'),
    ('Indonesian', 'ind'),
    ('Interlingua', 'ina'),
    ('Interlingue', 'ile'),
    ('Inuktitut', 'iku'),
    ('Inupiaq', 'ipk'),
    ('Irish', 'gle'),
    ('Italian', 'ita'),
    ('Japanese', 'jpn'),
    ('Javanese', 'jav'),
    ('Kannada', 'kan'),
    ('Kanuri', 'kau'),
    ('Kashmiri', 'kas'),
    ('Kazakh', 'kaz'),
    ('Central Khmer', 'khm'),
    ('Kikuyu', 'kik'),
    ('Kinyarwanda', 'kin'),
    ('Kyrgyz', 'kir'),
    ('Komi', 'kom'),
    ('Kongo', 'kon'),
    ('Korean', 'kor'),
    ('Kuanyama', 'kua'),
    ('Kurdish', 'kur'),
    ('Lao', 'lao'),
    ('Latin', 'lat'),
    ('Latvian', 'lav'),
    ('Limburgan', 'lim'),
    ('Lingala', 'lin'),
    ('Lithuanian', 'lit'),
    ('Luba-Katanga', 'lub'),
    ('Luxembourgish', 'ltz'),
    ('Macedonian', 'mkd'),
    ('Macedonian', 'mac'),
    ('Malagasy', 'mlg'),
    ('Malay', 'msa'),
    ('Malay', 'may'),
    ('Malayalam', 'mal'),
    ('Maltese', 'mlt'),
    ('Manx', 'glv'),
    ('`Maori`', 'mri'),
    ('`Maori`', 'mao'),
    ('Marathi', 'mar'),
    ('Marshallese', 'mah'),
    ('Mongolian', 'mon'),
    ('Nauru', 'nau'),
    ('Navajo', 'nav'),
    ('North Ndebele', 'nde'),
    ('South Ndebele', 'nbl'),
    ('Ndonga', 'ndo'),
    ('Nepali', 'nep'),
    ('Norwegian', 'nor'),
    ('Norwegian Bokmål', 'nob'),
    ('Norwegian Nynorsk', 'nno'),
    ('Occitan', 'oci'),
    ('Ojibwa', 'oji'),
    ('Oriya', 'ori'),
    ('Oromo', 'orm'),
    ('Ossetian', 'oss'),
    ('Pali', 'pli'),
    ('Pashto', 'pus'),
    ('Persian', 'fas'),
    ('Persian', 'per'),
    ('Polish', 'pol'),
    ('Portuguese', 'por'),
    ('Punjabi', 'pan'),
    ('Quechua', 'que'),
    ('Romanian', 'ron'),
    ('Romanian', 'rum'),
    ('Romansh', 'roh'),
    ('Rundi', 'run'),
    ('Russian', 'rus'),
    ('Northern Sami', 'sme'),
    ('Samoan', 'smo'),
    ('Sango', 'sag'),
    ('Sanskrit', 'san'),
    ('Sardinian', 'srd'),
    ('Serbian', 'srp'),
    ('Shona', 'sna'),
    ('Sindhi', 'snd'),
    ('Sinhala', 'sin'),
    ('Slovak', 'slk'),
    ('Slovak', 'slo'),
    ('Slovenian', 'slv'),
    ('Somali', 'som'),
    ('Southern Sotho', 'sot'),
    ('Spanish', 'spa'),
    ('Sundanese', 'sun'),
    ('Swahili', 'swa'),
    ('Swati', 'ssw'),
    ('Swedish', 'swe'),
    ('Tagalog', 'tgl'),
    ('Tahitian', 'tah'),
    ('Tajik', 'tgk'),
    ('Tamil', 'tam'),
    ('Tatar', 'tat'),
    ('Telugu', 'tel'),
    ('Thai', 'tha'),
    ('Tibetan', 'bod'),
    ('Tibetan', 'tib'),
    ('Tigrinya', 'tir'),
    ('Tonga', 'ton'),
    ('Tsonga', 'tso'),
    ('Tswana', 'tsn'),
    ('Turkish', 'tur'),
    ('Turkmen', 'tuk'),
    ('Twi', 'twi'),
    ('Uighur', 'uig'),
    ('Ukrainian', 'ukr'),
    ('Urdu', 'urd'),
    ('Uzbek', 'uzb'),
    ('Venda', 'ven'),
    ('Vietnamese', 'vie'),
    ('Volapük', 'vol'),
    ('Walloon', 'wln'),
    ('Welsh', 'cym'),
    ('Welsh', 'wel'),
    ('Wolof', 'wol'),
    ('Xhosa', 'xho'),
    ('Sichuan Yi', 'iii'),
    ('Yiddish', 'yid'),
    ('Yoruba', 'yor'),
    ('Zhuang', 'zha'),
    ('Zulu', 'zul'),

]

languages_2d = [
    ('Abkhazian', 'ab'),
    ('Afar', 'aa'),
    ('Afrikaans', 'af'),
    ('Akan', 'ak'),
    ('Albanian', 'sq'),
    ('Amharic', 'am'),
    ('Arabic', 'ar'),
    ('Aragonese', 'an'),
    ('Armenian', 'hy'),
    ('Assamese', 'as'),
    ('Avaric', 'av'),
    ('Avestan', 'ae'),
    ('Aymara', 'ay'),
    ('Azerbaijani', 'az'),
    ('Bambara', 'bm'),
    ('Bashkir', 'ba'),
    ('Basque', 'eu'),
    ('Belarusian', 'be'),
    ('Bengali', 'bn'),
    ('Bislama', 'bi'),
    ('Bosnian', 'bs'),
    ('Breton', 'br'),
    ('Bulgarian', 'bg'),
    ('Burmese', 'my'),
    ('Catalan', 'ca'),
    ('Chamorro', 'ch'),
    ('Chechen', 'ce'),
    ('Chichewa', 'ny'),
    ('Chinese', 'zh'),
    ('Church Slavonic', 'cu'),
    ('Chuvash', 'cv'),
    ('Cornish', 'kw'),
    ('Corsican', 'co'),
    ('Cree', 'cr'),
    ('Croatian', 'hr'),
    ('Czech', 'cs'),
    ('Danish', 'da'),
    ('Divehi', 'dv'),
    ('Dutch', 'nl'),
    ('Dzongkha', 'dz'),
    ('English', 'en'),
    ('Esperanto', 'eo'),
    ('Estonian', 'et'),
    ('Ewe', 'ee'),
    ('Faroese', 'fo'),
    ('Fijian', 'fj'),
    ('Finnish', 'fi'),
    ('French', 'fr'),
    ('Western Frisian', 'fy'),
    ('Fulah', 'ff'),
    ('Gaelic', 'gd'),
    ('Galician', 'gl'),
    ('Ganda', 'lg'),
    ('Georgian', 'ka'),
    ('German', 'de'),
    ('Greek', 'el'),
    ('Kalaallisut', 'kl'),
    ('Guarani', 'gn'),
    ('Gujarati', 'gu'),
    ('Haitian', 'ht'),
    ('Hausa', 'ha'),
    ('Hebrew', 'he'),
    ('Herero', 'hz'),
    ('Hindi', 'hi'),
    ('Hiri Motu', 'ho'),
    ('Hungarian', 'hu'),
    ('Icelandic', 'is'),
    ('Ido', 'io'),
    ('Igbo', 'ig'),
    ('Indonesian', 'id'),
    ('Interlingua', 'ia'),
    ('Interlingue', 'ie'),
    ('Inuktitut', 'iu'),
    ('Inupiaq', 'ik'),
    ('Irish', 'ga'),
    ('Italian', 'it'),
    ('Japanese', 'ja'),
    ('Javanese', 'jv'),
    ('Kannada', 'kn'),
    ('Kanuri', 'kr'),
    ('Kashmiri', 'ks'),
    ('Kazakh', 'kk'),
    ('Central Khmer', 'km'),
    ('Kikuyu', 'ki'),
    ('Kinyarwanda', 'rw'),
    ('Kyrgyz', 'ky'),
    ('Komi', 'kv'),
    ('Kongo', 'kg'),
    ('Korean', 'ko'),
    ('Kuanyama', 'kj'),
    ('Kurdish', 'ku'),
    ('Lao', 'lo'),
    ('Latin', 'la'),
    ('Latvian', 'lv'),
    ('Limburgan', 'li'),
    ('Lingala', 'ln'),
    ('Lithuanian', 'lt'),
    ('Luba-Katanga', 'lu'),
    ('Luxembourgish', 'lb'),
    ('Macedonian', 'mk'),
    ('Malagasy', 'mg'),
    ('Malay', 'ms'),
    ('Malayalam', 'ml'),
    ('Maltese', 'mt'),
    ('Manx', 'gv'),
    ('Maori', 'mi'),
    ('Marathi', 'mr'),
    ('Marshallese', 'mh'),
    ('Mongolian', 'mn'),
    ('Nauru', 'na'),
    ('Navajo', 'nv'),
    ('North Ndebele', 'nd'),
    ('South Ndebele', 'nr'),
    ('Ndonga', 'ng'),
    ('Nepali', 'ne'),
    ('Norwegian', 'no'),
    ('Norwegian Bokmål', 'nb'),
    ('Norwegian Nynorsk', 'nn'),
    ('Occitan', 'oc'),
    ('Ojibwa', 'oj'),
    ('Oriya', 'or'),
    ('Oromo', 'om'),
    ('Ossetian', 'os'),
    ('Pali', 'pi'),
    ('Pashto', 'ps'),
    ('Persian', 'fa'),
    ('Polish', 'pl'),
    ('Portuguese', 'pt'),
    ('Punjabi', 'pa'),
    ('Quechua', 'qu'),
    ('Romanian', 'ro'),
    ('Romansh', 'rm'),
    ('Rundi', 'rn'),
    ('Russian', 'ru'),
    ('Northern Sami', 'se'),
    ('Samoan', 'sm'),
    ('Sango', 'sg'),
    ('Sanskrit', 'sa'),
    ('Sardinian', 'sc'),
    ('Serbian', 'sr'),
    ('Shona', 'sn'),
    ('Sindhi', 'sd'),
    ('Sinhala', 'si'),
    ('Slovak', 'sk'),
    ('Slovenian', 'sl'),
    ('Somali', 'so'),
    ('Southern Sotho', 'st'),
    ('Spanish', 'es'),
    ('Sundanese', 'su'),
    ('Swahili', 'sw'),
    ('Swati', 'ss'),
    ('Swedish', 'sv'),
    ('Tagalog', 'tl'),
    ('Tahitian', 'ty'),
    ('Tajik', 'tg'),
    ('Tamil', 'ta'),
    ('Tatar', 'tt'),
    ('Telugu', 'te'),
    ('Thai', 'th'),
    ('Tibetan', 'bo'),
    ('Tigrinya', 'ti'),
    ('Tonga', 'to'),
    ('Tsonga', 'ts'),
    ('Tswana', 'tn'),
    ('Turkish', 'tr'),
    ('Turkmen', 'tk'),
    ('Twi', 'tw'),
    ('Uighur', 'ug'),
    ('Ukrainian', 'uk'),
    ('Urdu', 'ur'),
    ('Uzbek', 'uz'),
    ('Venda', 've'),
    ('Vietnamese', 'vi'),
    ('Volapük', 'vo'),
    ('Walloon', 'wa'),
    ('Welsh', 'cy'),
    ('Wolof', 'wo'),
    ('Xhosa', 'xh'),
    ('Sichuan Yi', 'ii'),
    ('Yiddish', 'yi'),
    ('Yoruba', 'yo'),
    ('Zhuang', 'za'),
    ('Zulu', 'zu'),
]
